---
title: "MB/MF_contribution, drug conditions"
output: html_document
---

```{r setup, include=FALSE}
source("libs/Librarries.R")
source("libs/plot/compare_mbmf_reg_plot.R")
```

```{r}
# four rows are related to intercept and MB, prob and their interaction
propmf <- readMat("data/Data_in_matlab/tot_MFprop_30.mat")
dopmf <- readMat("data/Data_in_matlab/tot_MFdop_30.mat")
placmf <- readMat("data/Data_in_matlab/tot_MFplac_30.mat")
propmb <- readMat("data/Data_in_matlab/tot_regparam_pro.mat")
dopmb <- readMat("data/Data_in_matlab/tot_regparam_dop.mat")
placmb <- readMat("data/Data_in_matlab/tot_regparam_plac.mat")
propmf <- propmf$tot.effects.with.intercept
dopmf <- dopmf$tot.effects.with.intercept
placmf <- placmf$tot.effects.with.intercept
propmb <- propmb$tot.effects.with.intercept
dopmb <- dopmb$tot.effects.with.intercept
placmb <- placmb$tot.effects.with.intercept
```

#MB contribution in Placebo condition, Figure 3B
```{r}
placmb_fix <- readMat("data/Data_in_matlab/coef_mbreg_plac.mat")
placsemb <- readMat("data/Data_in_matlab/se_mbreg_plac.mat")
means <- c(placmb_fix$coeff.MB[1, 1], placmb_fix$coeff.MB[2, 1], placmb_fix$coeff.MB[3, 1])
se <- c(placsemb$coeff.MB.SE[1, 1], placsemb$coeff.MB.SE[2, 1], placsemb$coeff.MB.SE[3, 1])


dt <- data.frame(ind = c(1:3), index = as.numeric(means), ss = as.numeric(se))

p <- ggplot(dt, aes(x = ind, y = index)) +
   scale_y_continuous(breaks = c(-0.5, 0, 0.5, 1), limits = c(-0.5, 2.1)) +
   geom_errorbar(aes(ymin = index - ss, ymax = index + ss), width = .0000001) +
   geom_point() +
   scale_x_continuous(breaks = 1:3, labels = c("Rew", "Prob", "Int"), limits = c(0.8, 3.2)) +
   xlab("") +
   ylab("beta") +
   theme_bw(base_size = 20) +
   theme(
      axis.title.y = element_text(hjust = 0.5),
      axis.line = element_line(colour = "black"),
      panel.border = element_blank(),
      panel.grid = element_blank(),
      panel.background = element_blank(),
      legend.background = element_blank()
   )
p
```



# Distribution plots to compare MB and MF contributions, Figures 3 C & G
```{r}
effectmf <- data.frame(propmf[2, ], placmf[2, ], dopmf[2, ])
p1 <- compare_mbmf_reg_plot(effectmf)


effectmb <- data.frame(propmb[2, ], placmb[2, ], dopmb[2, ])
p2 <- compare_mbmf_reg_plot(effectmb)
p2
```


```{r}
### Anova to compare Betas, influence of regressors, between drug conditions
coef <- 2
nsub <- 30
subs <- c(1:nsub)
tot_2opt <- c(propmb[coef, subs], dopmb[coef, subs], placmb[coef, subs])
drugname <- c(rep("p", nsub), rep("d", nsub), rep("pl", nsub))
meta <- data.frame(tot_2opt, drugname = as.factor(drugname))
res <- aov(tot_2opt ~ drugname, data = meta)
summary(res)
mbfval <- summary(res)[[1]][[1, "F value"]]
mbpval <- summary(res)[[1]][[1, "Pr(>F)"]]
# kruskal.test(tot_2opt~drugname , data = meta)
# t.test(placmb[coef,subs],dopmb[coef,subs])
```
