---
title: "Conf_on_MB"
output: html_document
---

We compared the influence on confidence on MB behavior in the next trial in three drug conditions, the analysis was done in Rani's code at Matlab, in the below i just show the plots.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE, error = FALSE, comment="", fig.align = "center" ) #,fig.width = 6,fig.height = 2
#library(lme)
library(ggplot2)
library(gridExtra)
library(readr)
library(tidyr)
library(dplyr)
library(cowplot)
library(firatheme)
library(lme4)
library(R.matlab)
library(merTools)

source("C:/Users/sershadmanesh/Nextcloud/Drug_study/plot/confMBplot.R")
source("/Users/sershadmanesh/Nextcloud/Drug_study/Public/plot/compare_mbmf_reg_plot.R")

taskdrug = readRDS("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/taskdrug2.rds") # the data including unchosen options
drug = readRDS("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/drug.rds")
drugday = readRDS("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/drugday_30")
param = readRDS("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/param_30_ordered")
```

```{r}
thsara =theme(axis.title.y = element_text(hjust = 0.5, size = 16),
          axis.title.x = element_text(size = 16),
          axis.text = element_text(size = 14),
            axis.line = element_line(colour = "black"),
            panel.border = element_blank(),
            panel.grid = element_blank(),
            panel.background = element_blank(),
            legend.position = "right",
            legend.background=element_blank()
      )
```

```{r}
confmb_pro = readMat("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/Data_in_matlab/tot_confMB_pro.mat")  # fixed+random, 30 subs
confmb_dop = readMat("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/Data_in_matlab/tot_confMB_dop.mat")
confmb_plac = readMat("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/Data_in_matlab/tot_confMB_plac.mat")
confmbpro = confmb_pro$tot.effects.with.intercept
confmbdop = confmb_dop$tot.effects.with.intercept
confmbplac = confmb_plac$tot.effects.with.intercept
confmbdrugs = list(confmbpro,confmbdop,confmbplac)
```

```{r}
### Anova to compare Betas, influence of regressors, between drug conditions
coef=4
#25,26,28
nsub=30
subs = c(1:30)
tot_2opt = c(confmbdrugs[[2]][coef,subs],confmbdrugs[[3]][coef,subs],confmbdrugs[[1]][coef,subs])
drugname = c(rep("p", nsub), rep("d", nsub), rep("pl", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname) )
res = aov(tot_2opt~drugname , data = meta)
cmbfval = summary(res)[[1]][[1,"F value"]]
cmbpval = summary(res)[[1]][[1,"Pr(>F)"]]
#kruskal.test(tot_2opt~drugname , data = meta) 
```
 # Nonparametric version of the above analysis
```{r}
### Anova to compare Betas, influence of regressors, between drug conditions
coef=2
niter = 1000
nsub=30
subs = c(1:nsub)
allcoef = c(confmbdrugs[[2]][coef,subs],confmbdrugs[[3]][coef,subs],confmbdrugs[[1]][coef,subs])
cmbrand = matrix(0,niter,2) # 2 is for fvalue and pvalue
for (iter in 1:niter){
  drugname = sample(c("p","d","pl"), length(allcoef),replace = TRUE)
  #drugname = c(rep("p", nsub), rep("d", nsub), rep("pl", nsub))
  meta = data.frame(allcoef,drugname = as.factor(drugname) )
  resaov = aov(allcoef~drugname , data = meta)
  cmbrand [iter,1] = summary(resaov)[[1]][[1,"F value"]]
  cmbrand [iter,2] = summary(resaov)[[1]][[1,"Pr(>F)"]]
}
#saveRDS(cmbrand, file= "/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/permutatedAnova_ConfonMB.rds")
cmbrand = readRDS( "/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/permutatedAnova_ConfonMB.rds")
length(which(cmbrand[,1]>cmbfval))/niter# 0.026 for 1000 iter, 0.0312 for 10^5


cmbran= data.frame(v=cmbrand[,1])
P = ggplot(cmbran,aes(x=v))+geom_histogram(bins =500, fill = "GOLD")+
  xlab("Group factor in ICB")+ylab("Frequency")+ xlim(0,13)+
    labs(title = "")+
    theme_bw( ) +thsara
P
```


# Posthoc test for the above nonparametric Anova
```{r}
coef=2
niter = 100000
nsub=30
subs = c(1:nsub)
ndrug=3
postrand = matrix(0,niter,ndrug) # 1 is Prop-plac, 2 is dop-plac, 3 is prop-dop
for (iter in 1:niter){
  twocoef = c(confmbdrugs[[1]][coef,subs],confmbdrugs[[3]][coef,subs])
  allsam= c(rep("p",nsub),rep("pl",nsub))
  drugname = sample(allsam, length(twocoef),replace = FALSE)
  meta = data.frame(twocoef,drugname = as.factor(drugname) )
  out = kruskal.test(twocoef~drugname , data = meta)
  postrand [iter,1] = out$statistic
  
  twocoef = c(confmbdrugs[[2]][coef,subs],confmbdrugs[[3]][coef,subs])
  allsam = c(rep("d",nsub),rep("pl",nsub))
  drugname = sample(allsam, length(twocoef),replace = FALSE)
  meta = data.frame(twocoef,drugname = as.factor(drugname) )
  out = kruskal.test(twocoef~drugname , data = meta) 
  postrand [iter,2] = out$statistic
  
  twocoef = c(confmbdrugs[[1]][coef,subs],confmbdrugs[[2]][coef,subs])
  allsam = c(rep("p",nsub),rep("d",nsub))
  drugname = sample(allsam, length(twocoef),replace = FALSE)
  meta = data.frame(twocoef,drugname = as.factor(drugname) )
  out = kruskal.test(twocoef~drugname , data = meta) 
  postrand [iter,3] = out$statistic
 
}
#saveRDS(postrand, file= "/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/permut_posthoc_CONFonMB.rds")
#length(which(postrand[,2]<11.263))/length(postrand[,2])# the empirical result for Dopamine influence on CONFMB

```

```{r}
coef=4
effectmf= data.frame(confmbdrugs[[1]][coef,],confmbdrugs[[3]][coef,],confmbdrugs[[2]][coef,])
p1 = compare_mbmf_reg_plot(effectmf)
p1
```
