---
title: "MB_contribute_simulated"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE, error = FALSE, comment="", fig.align = "center" ) 
library(ggplot2)
library(gridExtra)
library(readr)
library(tidyr)
library(gghalves)
library(dplyr)
library(cowplot)
library(lme4)
library(R.matlab)
source("/Users/sershadmanesh/Nextcloud/Drug_study/Public/accessory/input_mixedreg_MBcont_accessor.R")
source("/Users/sershadmanesh/Nextcloud/Drug_study/Public/simu/simu_choice_conf.R")
source("/Users/sershadmanesh/Nextcloud/Drug_study/Public/plot/compare_mbmf_reg_plot.R")
```


```{r}
taskdrug = readRDS("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/taskdrug2.rds")
drug = readRDS("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/drug.rds")
nsub=30
```

```{r}
# a theme for plots
thsara =theme(axis.title.y = element_text(hjust = 0.5, size = 16),
          axis.title.x = element_text(size = 16),
          axis.text = element_text(size = 14),
            axis.line = element_line(colour = "black"),
            panel.border = element_blank(),
            panel.grid = element_blank(),
            panel.background = element_blank(),
            legend.position = "right",
            legend.background=element_blank()
      )
```


```{r,fig.width = 1,fig.height = 1}
param = readRDS("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/fit_6param_30sub_100iter.rds")
nsub= 30
ndrug=3
nsimu = 1000
randeff = array(0, dim = c(ndrug,nsimu, nsub))

for (simu in 1:nsimu){
for (dru in 1:ndrug){ # take care!!
C_MB=c()
U_MB=c()
Y_MB=c()
SS_MB=c()
P_MB=c()
 for (sub in 1:nsub){
    drugpos = drug[sub,dru] 
    
    tasksub = taskdrug[which(taskdrug$subject==sub & taskdrug$day==drugpos), ] # subj for new 4 subjects!!!attention
  
    realized_reward = cbind(tasksub$reward.1, tasksub$reward.2, tasksub$reward.3, tasksub$reward.4)
    reward_prob= cbind(tasksub$prob.1, tasksub$prob.2, tasksub$prob.3, tasksub$prob.4)
    trials= cbind(tasksub$trials.1, tasksub$trials.2)
 
  ######### Simulation ########   
      ret = simu_choice_conf(param[[2]][dru,sub], param[[3]][dru,sub], param[[4]][dru,sub], param[[5]][dru,sub],
                 param[[6]][dru,sub], param[[7]][dru,sub], realized_reward, trials)
      chosen = ret[[1]]
      score = ret[[3]]
  ###preparing the input of mixed effect regression
      #confidence is not important for our MB contribution
    retreg = input_mixedreg_MBcont_accessor(chosen, score, sub, realized_reward, reward_prob, trials)
    
    Y_MB= c(Y_MB,retreg[[1]])
    C_MB= c(C_MB,retreg[[2]])
    SS_MB= c(SS_MB,retreg[[3]])
    P_MB= c(P_MB,retreg[[4]])
 } # sub
    N_MB= 1+rep(0,length(C_MB))
    prop = Y_MB/N_MB
    prop[which(N_MB==0)]=0
  
  MB_tbl_with_conf= data.frame(Y_MB, C_MB, SS_MB, P_MB, N_MB, prop)

  fitmix = glmer(prop ~  C_MB*P_MB+(C_MB*P_MB|SS_MB), data = MB_tbl_with_conf, weights = N_MB, family= binomial)
                
  f = summary(fitmix)
  randeff[dru,simu,] =  f$coefficients[2,1] + ranef(fitmix)$SS_MB[,2]  # random effect + fixed effect
} # dru
} # simu

#saveRDS(randeff,file="/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/mixedreg_MBcont_1000simu.rds")

```


```{r}
### Anova to compare Betas, influence of regressors, between drug conditions
randeff = readRDS("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/mixedreg_MBcont_1000simu.rds")
randof = apply(randeff,c(1,3), mean)
nsub=30
subs = c(1:nsub)
tot_2opt = c(randof[1,subs],randof[2,subs],randof[3,subs])
drugname = c(rep("p", nsub), rep("d", nsub), rep("pl", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname) )
aov(tot_2opt~drugname , data = meta) %>% summary() 
kruskal.test(tot_2opt~drugname , data = meta) 
```

```{r}
subs = c(1:30)
randcoef = c(randof[1,subs],randof[2,subs],randof[3,subs])
drugnam = c(rep("Prop",nsub),rep("Dop",nsub),rep("Plac",nsub))
df = data.frame(randcoef ,drugnam)
df$drug = factor(df$drug,levels = c("Prop","Dop","Plac"))

p =ggplot(df,aes(x = randcoef , fill  = drug))+
  geom_density(alpha = 0.5)+scale_fill_manual(values=c("red", "green","blue"))+xlab("Total effect")+ylab("Density")+
    labs(title = "")+ xlim(c(-1,4))+
    theme_bw( ) + thsara
p
```


```{r}
# three column plot
effectmb= data.frame(randof[1,subs],randof[2,subs],randof[3,subs])
p2 = compare_mbmf_reg_plot(effectmb)
p2
```

