---
title: "MB/MF_contribution, drug conditions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE, error = FALSE, comment="", fig.align = "center" ) #,fig.width = 6,fig.height = 2
library(ggplot2)
library(gridExtra)
library(readr)
library(tidyr)
library(dplyr)
library(cowplot)
library(gghalves)
library(lme4)
library(R.matlab)
```

```{r}
# The below fitting was at 10Nov.2022
# four rows are related to intercept and MB, prob and their interaction
propmf = readMat("/Users/sershadmanesh/Nextcloud/Drug_study/data/Data_in_matlab/tot_MFprop_30.mat")
dopmf = readMat("/Users/sershadmanesh/Nextcloud/Drug_study/data/Data_in_matlab/tot_MFdop_30.mat")
placmf = readMat("/Users/sershadmanesh/Nextcloud/Drug_study/data/Data_in_matlab/tot_MFplac_30.mat")
propmb = readMat("/Users/sershadmanesh/Nextcloud/Drug_study/data/Data_in_matlab/tot_regparam_pro.mat")
dopmb = readMat("/Users/sershadmanesh/Nextcloud/Drug_study/data/Data_in_matlab/tot_regparam_dop.mat")
placmb = readMat("/Users/sershadmanesh/Nextcloud/Drug_study/data/Data_in_matlab/tot_regparam_plac.mat")
propmf = propmf$tot.effects.with.intercept
dopmf = dopmf$tot.effects.with.intercept
placmf = placmf$tot.effects.with.intercept
propmb = propmb$tot.effects.with.intercept
dopmb = dopmb$tot.effects.with.intercept 
placmb = placmb$tot.effects.with.intercept
```


# colorful distribution plots to compare MB and MF contributions
```{r}
effectmf= data.frame(propmf[2,],placmf[2,],dopmf[2,])
p1 = compare_mbmf_reg_plot(effectmf)
effectmb= data.frame(propmb[2,],placmb[2,],dopmb[2,])
p2 = compare_mbmf_reg_plot(effectmb)
p2
```


```{r}
### Anova to compare Betas, influence of regressors, between drug conditions
coef=2
nsub=30
subs = c(1:nsub)
tot_2opt = c(propmb[coef,subs], dopmb[coef,subs],placmb[coef,subs])
drugname = c(rep("p", nsub), rep("d", nsub), rep("pl", nsub))
meta = data.frame(tot_2opt,drugname = as.factor(drugname) )
res= aov(tot_2opt~drugname , data = meta) 
summary(res)
mbfval = summary(res)[[1]][[1,"F value"]]
mbpval = summary(res)[[1]][[1,"Pr(>F)"]]
#kruskal.test(tot_2opt~drugname , data = meta) 
#t.test(placmb[coef,subs],dopmb[coef,subs])

```


# Nonparametric version of the above analysis
```{r}
### Anova to compare Betas, influence of regressors, between drug conditions
coef=2
niter = 1000
nsub=30
subs = c(1:nsub)
allcoef = c(dopmb[coef,subs],placmb[coef,subs],propmb[coef,subs])
fprand = matrix(0,niter,2) # 2 is for fvalue and pvalue
for (iter in 1:niter){
  allsam= c(rep("p",nsub),rep("d",nsub),rep("pl",nsub))
  drugname = sample(allsam, length(allcoef),replace = FALSE)
  #drugname = c(rep("p", nsub), rep("d", nsub), rep("pl", nsub))
  meta = data.frame(allcoef,drugname = as.factor(drugname) )
  resaov = aov(allcoef~drugname , data = meta)
  fprand [iter,1] = summary(resaov)[[1]][[1,"F value"]]
  fprand [iter,2] = summary(resaov)[[1]][[1,"Pr(>F)"]]
 
}
#saveRDS(fprand, file= "/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/permutatedAnova_MB.rds")
#fprand= readRDS("/Users/sershadmanesh/Nextcloud/Drug_study/Public/data/permutatedAnova_MB.rds")
which(fprand[,1]>mbfval)

length(which(fprand[,1]>mbfval))/niter
fpran= data.frame(v=fprand[,1])

P = ggplot(fpran,aes(x=v))+geom_histogram(bins =500, fill = "GOLD")+
  xlab("MB contribution")+ylab("Frequency")+ xlim(0,8)+
    labs(title = "")+
    theme_bw( ) +thsara
P

```


# Posthoc test for the above nonparametric Anova
```{r}
coef=2
niter = 100000
nsub=30
subs = c(1:nsub)
ndrug=3
postrand = matrix(0,niter,ndrug) # 1 is Prop-plac, 2 is dop-plac, 3 is prop-dop
for (iter in 1:niter){
  twocoef = c(propmb[coef,subs],placmb[coef,subs])
  allsam= c(rep("p",nsub),rep("pl",nsub))
  drugname = sample(allsam, length(twocoef),replace = FALSE)
  meta = data.frame(twocoef,drugname = as.factor(drugname) )
  out = kruskal.test(twocoef~drugname , data = meta)
  postrand [iter,1] = out$statistic
  
  twocoef = c(dopmb[coef,subs],placmb[coef,subs])
  allsam = c(rep("d",nsub),rep("pl",nsub))
  drugname = sample(allsam, length(twocoef),replace = FALSE)
  meta = data.frame(twocoef,drugname = as.factor(drugname) )
  out = kruskal.test(twocoef~drugname , data = meta) 
  postrand [iter,2] = out$statistic
  
  twocoef = c(propmb[coef,subs],dopmb[coef,subs])
  allsam = c(rep("p",nsub),rep("d",nsub))
  drugname = sample(allsam, length(twocoef),replace = FALSE)
  meta = data.frame(twocoef,drugname = as.factor(drugname) )
  out = kruskal.test(twocoef~drugname , data = meta) 
  postrand [iter,3] = out$statistic
 
}
#saveRDS(postrand, file= "/Users/sershadmanesh/Nextcloud/Drug_study/data/permut_posthoc_MB.rds")

```

